
version: '3.2'

networks:
    skcript:
        external: 
            name: skcript

services:

    ca_org2:
        networks:
            skcript:
                aliases:
                    - ca_org2
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == 18.191.61.173
                    - engine.labels.aws.region == us-east-2
                preferences:
                    -  spread: node.labels.aws.zone
        image: hyperledger/fabric-ca:amd64-1.4.4
        hostname: ca.org2.example.com
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca_org2
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/395946c9f5be25d7b66830101418e7fe3011f789b1b853a4139500cd7c79523a_sk
        ports:
            - "8054:7054"   
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
        volumes:
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config

    couchdb0_org2:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == 18.191.61.173
                    - engine.labels.aws.region == us-east-2
                preferences:
                    -  spread: node.labels.aws.zone
        image: hyperledger/fabric-couchdb:amd64-0.4.18
        hostname: couchdb0_org2
        networks:
           - skcript

    couchdb1_org2:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == 18.191.61.173
                    - engine.labels.aws.region == us-east-2
                preferences:
                    -  spread: node.labels.aws.zone
        image: hyperledger/fabric-couchdb:amd64-0.4.18
        hostname: couchdb1_org2
        networks:
           - skcript
