
version: '3.2'

networks:
    skcript:
        external: 
            name: skcript

services:

    ca_org1:
        networks:
            skcript:
                aliases:
                    - ca_org1
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == ip-172-31-13-137
                    - engine.labels.aws.region == us-east-2
        image: hyperledger/fabric-ca:amd64-1.4.4
        hostname: ca.org1.example.com
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca_org1
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/b6e9a135c6772f706f8ecef5b65f68a37e52b54977b24615db5f9d5d0ca436ae_sk
        ports:
            - "7054:7054"   
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
        volumes:
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config

    cli:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == ip-172-31-13-137
                    - engine.labels.aws.region == us-east-2
        image: hyperledger/fabric-tools:amd64-1.4.4
        tty: true
        hostname: cli
        environment:
          - GOPATH=/opt/gopath
          - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
          - FABRIC_LOGGING_SPEC=debug
          - CORE_PEER_ID=cli.org1.example.com
          - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
          - CORE_PEER_LOCALMSPID=Org1MSP
          - CORE_CHAINCODE_KEEPALIVE=10
          - CORE_PEER_TLS_ENABLED=true
          - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
          - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
          - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
          - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
          
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: /bin/bash
        volumes:
            - /var/run/:/host/var/run/
            - /var/mynetwork/chaincode:/opt/gopath/src/github.com/chaincode
            #- /var/mynetwork/fabric-src/hyperledger/fabric:/opt/gopath/src/github.com/hyperledger/fabric
            - /var/mynetwork/certs/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
            - /var/mynetwork/certs/config:/var/hyperledger/config
            - /var/mynetwork/bin/:/var/bin
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/var/hyperledger/msp
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/var/hyperledger/tls
            # - /var/mynetwork/bin/jq:/usr/local/bin/jq
        networks:
            - skcript

    couchdb0_org1:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == ip-172-31-13-137
                    - engine.labels.aws.region == us-east-2
        image: hyperledger/fabric-couchdb:amd64-0.4.18
        hostname: couchdb0_org1
        ports:
           - 5984:5984
        networks:
           - skcript    

    couchdb1_org1:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == ip-172-31-13-137
                    - engine.labels.aws.region == us-east-2
        image: hyperledger/fabric-couchdb:amd64-0.4.18
        hostname: couchdb1_org1
        ports:
           - 6984:5984
        networks:
           - skcript    
